name: CI

on: [push, pull_request]

env:
  fail-fast: false

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v5
      - uses: actions/cache@v5
        name: Configure npm caching
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/CI.yml') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Run prettier
        run: |-
          npm i
          npx prettier --check .

  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.1', '8.2', '8.3', '8.4', '8.5']
        symfony-versions: ['6.4.*', '7.4.*', '8.0.*']
        exclude:
          - php-versions: '8.1'
            symfony-versions: '7.4.*'
          - php-versions: '8.1'
            symfony-versions: '8.0.*'
          - php-versions: '8.2'
            symfony-versions: '8.0.*'
          - php-versions: '8.3'
            symfony-versions: '8.0.*'

    name: Tests on PHP ${{ matrix.php-versions }} / Symfony ${{ matrix.symfony-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none

      - name: Install dependencies
        run: |-
          composer require \
            symfony/config:${{ matrix.symfony-versions }} \
            symfony/dependency-injection:${{ matrix.symfony-versions }} \
            symfony/http-kernel:${{ matrix.symfony-versions }} \
            symfony/twig-bundle:${{ matrix.symfony-versions }} \
            symfony/http-client:${{ matrix.symfony-versions }} \
            symfony/security-csrf:${{ matrix.symfony-versions }} \
            symfony/phpunit-bridge:${{ matrix.symfony-versions }} \
            symfony/property-access:${{ matrix.symfony-versions }} \
            symfony/serializer:${{ matrix.symfony-versions }} \
            symfony/framework-bundle:${{ matrix.symfony-versions }} \
            symfony/var-dumper:${{ matrix.symfony-versions }} \
            symfony/yaml:${{ matrix.symfony-versions }} \
            --ansi \
            --no-interaction \
            --no-progress \
            --with-all-dependencies

      - name: PHPUnit Tests
        run: vendor/bin/simple-phpunit
